-- TBC Phase 3 Leatherworking crafts that consume Heart of Darkness.
-- Patterns from Black Temple (Okuno / drops). Item IDs: wowhead.com/tbc/item=
-- HoD costs from recipe reagents (Anniversary Phase 3).

GuildieCrafts_LeatherworkingCrafts = {
    {
        name = "Bindings of Lightning Reflexes",
        itemId = 32574,
        hodCost = 4,
        category = "Physical DPS",
        slot = "Wrist",
        class = "Mail",
        bind = "BoE",
        notes = "Agility/haste bracers for hunters and enhancement shamans",
    },
    {
        name = "Shoulders of Lightning Reflexes",
        itemId = 32575,
        hodCost = 2,
        category = "Physical DPS",
        slot = "Shoulder",
        class = "Mail",
        bind = "BoP",
    },
    {
        name = "Swiftstrike Bracers",
        itemId = 32580,
        hodCost = 4,
        category = "Physical DPS",
        slot = "Wrist",
        class = "Leather",
        bind = "BoE",
        notes = "Strong leather DPS bracers",
    },
    {
        name = "Swiftstrike Shoulders",
        itemId = 32581,
        hodCost = 2,
        category = "Physical DPS",
        slot = "Shoulder",
        class = "Leather",
        bind = "BoP",
    },
    {
        name = "Living Earth Bindings",
        itemId = 32577,
        hodCost = 4,
        category = "Healer",
        slot = "Wrist",
        class = "Mail",
        bind = "BoE",
    },
    {
        name = "Living Earth Shoulders",
        itemId = 32579,
        hodCost = 2,
        category = "Healer",
        slot = "Shoulder",
        class = "Mail",
        bind = "BoP",
    },
    {
        name = "Bracers of Renewed Life",
        itemId = 32582,
        hodCost = 4,
        category = "Healer",
        slot = "Wrist",
        class = "Leather",
        bind = "BoE",
    },
    {
        name = "Shoulderpads of Renewed Life",
        itemId = 32583,
        hodCost = 2,
        category = "Healer",
        slot = "Shoulder",
        class = "Leather",
        bind = "BoP",
    },
    -- Mail — Shackled Souls (hunters / enhancement shamans)
    {
        name = "Bracers of Shackled Souls",
        itemId = 32399,
        hodCost = 1,
        category = "Shadow Resist",
        slot = "Wrist",
        class = "Mail",
        bind = "BoE",
        set = "Shackled Souls",
    },
    {
        name = "Waistguard of Shackled Souls",
        itemId = 32397,
        hodCost = 2,
        category = "Shadow Resist",
        slot = "Waist",
        class = "Mail",
        bind = "BoE",
        set = "Shackled Souls",
    },
    {
        name = "Greaves of Shackled Souls",
        itemId = 32400,
        hodCost = 3,
        category = "Shadow Resist",
        slot = "Legs",
        class = "Mail",
        bind = "BoE",
        set = "Shackled Souls",
    },
    {
        name = "Boots of Shackled Souls",
        itemId = 32398,
        hodCost = 2,
        category = "Shadow Resist",
        slot = "Feet",
        class = "Mail",
        bind = "BoE",
        set = "Shackled Souls",
    },

    -- Leather — Redeemed Soul (druids / rogues)
    {
        name = "Redeemed Soul Wristguards",
        itemId = 32395,
        hodCost = 1,
        category = "Shadow Resist",
        slot = "Wrist",
        class = "Leather",
        bind = "BoE",
        set = "Redeemed Soul",
    },
    {
        name = "Redeemed Soul Cinch",
        itemId = 32393,
        hodCost = 2,
        category = "Shadow Resist",
        slot = "Waist",
        class = "Leather",
        bind = "BoE",
        set = "Redeemed Soul",
    },
    {
        name = "Redeemed Soul Legguards",
        itemId = 32396,
        hodCost = 3,
        category = "Shadow Resist",
        slot = "Legs",
        class = "Leather",
        bind = "BoE",
        set = "Redeemed Soul",
    },
    {
        name = "Redeemed Soul Moccasins",
        itemId = 32394,
        hodCost = 2,
        category = "Shadow Resist",
        slot = "Feet",
        class = "Leather",
        bind = "BoE",
        set = "Redeemed Soul",
    },
}

GuildieCrafts_LeatherworkingCraftCategories = {
    "Physical DPS",
    "Healer",
    "Shadow Resist",
}
